### PR TITLE
Update error in body.html

### PR DESCRIPTION
**Pull request by ingmoyete**
Change variable name otherwise it is undefined and throws an error

**What problem is this solving?**

It throws an error because a variable is undefined.

**How should this be manually tested?**

Install app and go to store. Script should load

### CODE REVIEW

**Comment by ingmoyete** [comment]
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [x]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

**Comment by ingmoyete** [comment]
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [x]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

**Comment by ingmoyete** [comment]
Hi, how can we merge this commit?

**Comment by klzns** [comment]
Sorry for the delay! Thanks for contributing.

@allcontributors add @ingmoyete for code

**Pull request merged**
