### PR TITLE
First version

### PR DESCRIPTION
**Pull request by ingmoyete**
**What problem is this solving?**

New features

**How should this be manually tested?**
Just run store and test chat display

**Screenshots or example usage:** None

### CODE REVIEW

**Comment by ingmoyete** [comment]
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [ ]  Patch (backwards-compatible bug fixes)
> * [x]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

**Comment by ingmoyete** [comment]
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [x]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

**Comment by klzns** [comment]
Hi @ingmoyete thanks for the pull request. Do you mind letting me push some changes?
Here are the instructions:
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

If that doesnt work, maybe you need to open a pull request from a branch different from master of your repo.

**Comment by klzns** [comment]
I did the changes in this branch:
https://github.com/vtex-apps/oct8ne/tree/feature/events

Can you test if this works out?

**Comment by ingmoyete** [comment]
> Thanks for the update!
> 
> I would like to change some things related to the doc structure, so I'll open a PR separately. Is this app already in production i.e. ready to be published on VTEX IO Release Notes?

Yes, it is ready. I would need to test it when it is merged to master though. I can let you know when my testing is done. by "doc structure" you mean the files in the metadata folder?.

**Comment by ingmoyete** [comment]
> Hi @ingmoyete thanks for the pull request.
> 
> Do you mind letting me push some changes? Here are the instructions:
> https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork
> 
> If that doesnt work, maybe you need to open a pull request from a branch different from master of your repo.

Hi, yes you can make any changes you want. I will enable "allow changes to pull request..."  next time so you can make changes in that branch directly.

**Comment by ingmoyete** [comment]
> I did the changes in this branch:
> https://github.com/vtex-apps/oct8ne/tree/feature/events
> 
> Can you test if this works out?

Hi,
I tried to do "vtex link" and found this error below:
image

Ive already requested acces in the form as the error says.

image

How can we fix this?

**Comment by klzns** [comment]
@ingmoyete which account are you testing? 

Can you run `vtex whoami`?

**Comment by klzns** [comment]
There was issue on our side. Can you try it now?

**Comment by ingmoyete** [comment]
> There was issue on our side. Can you try it now?

Now it works. I could run the command "vtex link" and test it. 

The code you added had a problem that did not allow oct8ne to get the customer data. I did a fix in the index.tsx and created a pull request for it "https://github.com/vtex-apps/oct8ne/pull/5"

Let me know if those changes are ok for you

**Comment by klzns** [comment]
Closing this in favor of #6

**Pull request closed without merging**
